### ISSUE TITLE
Managing Flutter Version Discrepancies and Resolving Linter Issues in an Updated Project

### ISSUE THREAD

**Issue by HalaSalim77** [onestudio-co/flutter-bond#103]
PART OF GTC OPEN SOURCE INTIATIVE

Issue Description:
While updating an old Flutter project to the latest APIs, we encountered challenges with managing Flutter version discrepancies and faced numerous linter issues. This issue focuses on resolving the version conflicts and addressing the linter issues to ensure the project is up-to-date and adheres to best coding practices.

Key Objectives:
1. Identify the specific Flutter version discrepancies within the project, including inconsistencies between the project's SDK version and the Flutter version used for development.
2. Analyze and document the linter issues that arose after updating the project to the latest APIs.
3. Update the project's Flutter SDK to a compatible version with the latest APIs, considering factors such as stability and compatibility with the project's dependencies.
4. Resolve any version conflicts and ensure the project's dependencies are compatible with the updated Flutter SDK version.
5. Review and address the linter issues reported, following best coding practices and adhering to the project's style guide.
6. Update deprecated APIs, libraries, and methods to their recommended alternatives.
7. Optimize the project's codebase to improve performance and readability where possible.
8. Test the updated project thoroughly to verify the resolution of version conflicts and the successful resolution of linter issues.
9. Document the steps taken to manage the Flutter version discrepancies and resolve the linter issues, providing guidelines for future updates and maintenance.
10. Share knowledge and provide recommendations on managing Flutter version updates and handling linter issues effectively.

**Comment by salahamassi** [comment]
Done 
<img width="1957" alt="image" src="https://github.com/onestudio-co/flutter-bond/assets/17902030/7ef3d3b6-4926-4c77-b00c-dd6d32cfabd2">
