### ISSUE TITLE
'name' field doesn't match expected name 'bond_core'

### ISSUE THREAD

**Issue by SajaHerez** [onestudio-co/flutter-bond#114]
Part of GTC open source intiative

### Description :
When running "flutter pub get" in the "flutter-bond" project, a dependency resolution error occurs. The error message suggests a mismatch in the "name" field of the "pubspec.yaml" file.

### Steps to Reproduce :
Clone the "flutter-bond" project.
Run "flutter pub get" in the project directory.

### Expected Behavior :
The "flutter pub get" command should successfully resolve the project dependencies.

### Actual Behavior
The command fails with the following error message: "Error on line 1, column 7: 'name' field doesn't match expected name 'bond_core'."

###Screenshots/Code Snippets
Running "flutter pub get" in flutter-bond...
Resolving dependencies...
Error on line 1, column 7: "name" field doesn't match expected name "bond_core".
  ╷
1 │ name: bond_core_workspace
  │       ^^^^^^^^^^^^^^^^^^^
  ╵
pub get failed

###Version Info :
Flutter version: | 3.7.7

###Possible Solution :
Updating the "name" field in the "pubspec.yaml" file to match the expected name "bond_core" should resolve the issue.

**Comment by hussendev** [comment]
I'm having the same problem, I changed the name of the library to "bond_core_workspace"
But inside the files, that import is from "package:bond_core/core.dart"
This file does not exist

**Comment by hussendev** [comment]
> I'm having the same problem, I changed the name of the library to "bond_core_workspace" But inside the files, that import is from "package:bond_core/core.dart" This file does not exist


After searching, I found the following information:

 The bond_core library was uploaded to "pub.dev." This library is built on the foundations of bond_network, bond_cache, bond_notifications, and bond_form. I have worked around this issue. However, the two remaining libraries, app_analytics, and chat_bot, are not loaded yet.
