### ISSUE TITLE
Clear set-up steps in Contributing.md file

### ISSUE THREAD

**Issue by AbedrahmanYassen** [onestudio-co/flutter-bond#124]
PART OF GTC OPEN SOURCE INTIATIVE

## Description

When I first came to contribute to the project, I couldn't understand how to run the project, because there is no guidance on how to setup the project. So it would be an amazing idea to add more details on the contributing.md on how to get started.

**Comment by salahamassi** [comment]
check this https://github.com/onestudio-co/flutter-bond/pull/128
