### ISSUE TITLE
Simply clicking on the option to change the language switches to the other language without choosing a specific language.

### ISSUE THREAD

**Issue by MohDaqqa** [onestudio-co/flutter-bond#78]
PART OF GTC OPEN SOURCE INTIATIVE

**Comment by mohamedalwhaidi** [comment]
Hello @MohDaqqa

Thank you for taking the time to report this issue and contribute to our project. We really appreciate your input and your help to make Flutter-bond even better!

Upon reviewing the issue you mentioned, it seems that the current behavior, while perhaps not intuitive in the traditional sense, actually works as intended given the current structure of the application. At present, we only support two languages, and hence the switch mechanism was designed to quickly toggle between these without the need for a pop-up selection.

However, we recognize your point about expanding functionality as the project evolves and more languages and features might be added. 

If you want to help us, we suggestion for a create MorePage within the nav_bar that includes the options to change language, theme, and logout is a good idea, and we'd be thrilled if you want to contribute to its development.

This MorePage would be particularly useful for accommodating additional languages and features in the future, as well as enhancing overall navigation within the app.

Feel free to create a new feature request for this enhancement, or better yet, submit a Pull Request implementing it. We'll be more than happy to review your contribution and provide any necessary support or feedback.

Thank you once again for your valuable contribution to our open-source project. We look forward to seeing more of your innovative ideas and solutions in the future!

Best regards,
Mohamed Alwhaidi
