### ISSUE TITLE
validation on username not clear

### ISSUE THREAD

**Issue by Mamoun2020** [onestudio-co/flutter-bond#97]
PART OF GTC OPEN SOURCE INTIATIVE

Just entering a letter in the username field shows an immediate error message without explaining how the name can be until it is accepted.

**Comment by salahamassi** [comment]
this will solve automatically when we use a form Bond.

**Comment by salahamassi** [comment]
Thanks for your contribution

we plan to use [bond form ](https://github.com/onestudio-co/bond-docs/blob/main/forms.md)for register page and login page and validation rules
